/**
 * MassPay API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@masspay.io
 *
 * NOTE: This file is auto generated.
 * Do not edit the file manually.
 */
export { MasspayJsSdk } from './src/MasspayJsSdk';

export { ApiError } from './src/core/ApiError';
export { BaseHttpRequest } from './src/core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './src/core/CancelablePromise';
export { OpenAPI } from './src/core/OpenAPI';
export type { OpenAPIConfig } from './src/core/OpenAPI';

export type { _limit } from './src/models/_limit';
export type { _populate } from './src/models/_populate';
export type { _skip } from './src/models/_skip';
export type { _sort } from './src/models/_sort';
export type { AddUBORequest } from './src/models/AddUBORequest';
export type { alipay } from './src/models/alipay';
export type { AllAttributesResp } from './src/models/AllAttributesResp';
export type { AlreadyHasActiveDiscount } from './src/models/AlreadyHasActiveDiscount';
export type { ApiResponse } from './src/models/ApiResponse';
export type { applepay } from './src/models/applepay';
export { AttrsRequirement } from './src/models/AttrsRequirement';
export type { AttrTxn } from './src/models/AttrTxn';
export type { AttrValue } from './src/models/AttrValue';
export type { AttrVelocityRequest } from './src/models/AttrVelocityRequest';
export type { AutopayoutResp } from './src/models/AutopayoutResp';
export type { AutopayRule } from './src/models/AutopayRule';
export type { AvailableBalanceTxnResp } from './src/models/AvailableBalanceTxnResp';
export { BankAccount } from './src/models/BankAccount';
export { BankAccountCreate } from './src/models/BankAccountCreate';
export type { BankAccountGet } from './src/models/BankAccountGet';
export type { BankAccountUpdate } from './src/models/BankAccountUpdate';
export type { bcmc } from './src/models/bcmc';
export type { belfius } from './src/models/belfius';
export type { bitpay } from './src/models/bitpay';
export type { bpwallet } from './src/models/bpwallet';
export type { Card_0 } from './src/models/Card_0';
export type { Card_1 } from './src/models/Card_1';
export type { CardAddLink } from './src/models/CardAddLink';
export type { CardAddLinkCreate } from './src/models/CardAddLinkCreate';
export type { CardAddLinkGet } from './src/models/CardAddLinkGet';
export type { cardexternal } from './src/models/cardexternal';
export type { CardGet } from './src/models/CardGet';
export { CardResp } from './src/models/CardResp';
export type { CardUpdate } from './src/models/CardUpdate';
export { Chargeback } from './src/models/Chargeback';
export type { ChargebackAggregate } from './src/models/ChargebackAggregate';
export type { ChargebackAggregateStats } from './src/models/ChargebackAggregateStats';
export type { ChargebackAggregateStatsAmount } from './src/models/ChargebackAggregateStatsAmount';
export type { ChargebackAggregateStatsCount } from './src/models/ChargebackAggregateStatsCount';
export type { ChargebackGet } from './src/models/ChargebackGet';
export { Checkout } from './src/models/Checkout';
export type { CheckoutCreate } from './src/models/CheckoutCreate';
export type { CheckoutGet } from './src/models/CheckoutGet';
export type { CheckoutUpdate } from './src/models/CheckoutUpdate';
export type { CompaniesResp } from './src/models/CompaniesResp';
export type { Company } from './src/models/Company';
export type { Country } from './src/models/Country';
export type { Create } from './src/models/Create';
export type { CreateStatus } from './src/models/CreateStatus';
export { CreateSubaccountTxn } from './src/models/CreateSubaccountTxn';
export type { CreateUpdate } from './src/models/CreateUpdate';
export type { CreateUpdateStatus } from './src/models/CreateUpdateStatus';
export type { creditclick } from './src/models/creditclick';
export { Customer } from './src/models/Customer';
export type { CustomerAggregate } from './src/models/CustomerAggregate';
export type { CustomerAggregateBest } from './src/models/CustomerAggregateBest';
export type { CustomerAggregateBestDetails } from './src/models/CustomerAggregateBestDetails';
export type { CustomerAggregateStats } from './src/models/CustomerAggregateStats';
export type { CustomerAggregateStatsCount } from './src/models/CustomerAggregateStatsCount';
export type { CustomerCreate } from './src/models/CustomerCreate';
export type { CustomerGet } from './src/models/CustomerGet';
export { CustomerStatusHistory } from './src/models/CustomerStatusHistory';
export type { CustomerUpdate } from './src/models/CustomerUpdate';
export type { DeleteSuccess } from './src/models/DeleteSuccess';
export type { directdebit } from './src/models/directdebit';
export type { directdebitplus } from './src/models/directdebitplus';
export type { dummy } from './src/models/dummy';
export type { eps } from './src/models/eps';
export type { ErasureRequestSuccess } from './src/models/ErasureRequestSuccess';
export { Error400 } from './src/models/Error400';
export { Error401 } from './src/models/Error401';
export { Error403 } from './src/models/Error403';
export { Error404 } from './src/models/Error404';
export { Error405 } from './src/models/Error405';
export { Error409 } from './src/models/Error409';
export { Error500 } from './src/models/Error500';
export { Error504 } from './src/models/Error504';
export type { etransfer } from './src/models/etransfer';
export type { Exception } from './src/models/Exception';
export type { ezeewallet } from './src/models/ezeewallet';
export type { finshark } from './src/models/finshark';
export type { FoundUser } from './src/models/FoundUser';
export type { gcash } from './src/models/gcash';
export type { giropay } from './src/models/giropay';
export type { googlepay } from './src/models/googlepay';
export type { ideal } from './src/models/ideal';
export type { IdealIssuer } from './src/models/IdealIssuer';
export { IDUpload } from './src/models/IDUpload';
export type { imps } from './src/models/imps';
export type { interac } from './src/models/interac';
export { KYCSession } from './src/models/KYCSession';
export { Loads } from './src/models/Loads';
export type { LoadTxn } from './src/models/LoadTxn';
export { LoadTxnResp } from './src/models/LoadTxnResp';
export type { login } from './src/models/login';
export { LoginDefault } from './src/models/LoginDefault';
export type { LoginLogin } from './src/models/LoginLogin';
export type { LoginMFA } from './src/models/LoginMFA';
export { LoginMFASetUp } from './src/models/LoginMFASetUp';
export { LoginResponse } from './src/models/LoginResponse';
export type { Mcc } from './src/models/Mcc';
export { mfa } from './src/models/mfa';
export { MiddlewareGet } from './src/models/MiddlewareGet';
export type { multibanco } from './src/models/multibanco';
export type { mybank } from './src/models/mybank';
export type { NotFound } from './src/models/NotFound';
export type { ObjectHasTransactions } from './src/models/ObjectHasTransactions';
export type { opennode } from './src/models/opennode';
export type { Organisation } from './src/models/Organisation';
export type { OrganisationContact } from './src/models/OrganisationContact';
export type { OrganisationContactCreate } from './src/models/OrganisationContactCreate';
export type { OrganisationContactGet } from './src/models/OrganisationContactGet';
export type { OrganisationContactUpdate } from './src/models/OrganisationContactUpdate';
export type { OrganisationCreate } from './src/models/OrganisationCreate';
export type { OrganisationGet } from './src/models/OrganisationGet';
export type { OrganisationHierarchy } from './src/models/OrganisationHierarchy';
export type { OrganisationUpdate } from './src/models/OrganisationUpdate';
export type { p24 } from './src/models/p24';
export { PaymentLink } from './src/models/PaymentLink';
export type { PaymentLinkCreate } from './src/models/PaymentLinkCreate';
export type { PaymentLinkDetailCreate } from './src/models/PaymentLinkDetailCreate';
export type { PaymentLinkDetailGet } from './src/models/PaymentLinkDetailGet';
export type { PaymentLinkGet } from './src/models/PaymentLinkGet';
export type { PaymentProfile } from './src/models/PaymentProfile';
export type { PaymentProfileCreate } from './src/models/PaymentProfileCreate';
export type { PaymentProfileGet } from './src/models/PaymentProfileGet';
export type { PaymentProfileUpdate } from './src/models/PaymentProfileUpdate';
export type { PayoutTxn } from './src/models/PayoutTxn';
export { PayoutTxnCommitResp } from './src/models/PayoutTxnCommitResp';
export { PayoutTxnResp } from './src/models/PayoutTxnResp';
export type { paypal } from './src/models/paypal';
export type { paysafecard } from './src/models/paysafecard';
export type { paytm } from './src/models/paytm';
export type { payu } from './src/models/payu';
export { Plan } from './src/models/Plan';
export { PlanCreate } from './src/models/PlanCreate';
export type { PlanGet } from './src/models/PlanGet';
export type { PlanUpdate } from './src/models/PlanUpdate';
export type { pos } from './src/models/pos';
export type { ProcessorId } from './src/models/ProcessorId';
export type { ProcessorList } from './src/models/ProcessorList';
export type { Refund } from './src/models/Refund';
export type { RefundAggregate } from './src/models/RefundAggregate';
export type { RefundAggregateStats } from './src/models/RefundAggregateStats';
export type { RefundAggregateStatsCount } from './src/models/RefundAggregateStatsCount';
export type { RefundAggregateStatsVolume } from './src/models/RefundAggregateStatsVolume';
export type { RefundCreate } from './src/models/RefundCreate';
export type { RefundGet } from './src/models/RefundGet';
export { Report } from './src/models/Report';
export type { ReportCreate } from './src/models/ReportCreate';
export { ReportFilterRules } from './src/models/ReportFilterRules';
export type { ReportGet } from './src/models/ReportGet';
export { ReportSchedule } from './src/models/ReportSchedule';
export { ReportScheduleCreate } from './src/models/ReportScheduleCreate';
export type { ReportScheduleGet } from './src/models/ReportScheduleGet';
export type { ResetAPIKey } from './src/models/ResetAPIKey';
export type { ResourceInvalid } from './src/models/ResourceInvalid';
export type { Role } from './src/models/Role';
export type { Roles } from './src/models/Roles';
export { Routing } from './src/models/Routing';
export { RoutingCreate } from './src/models/RoutingCreate';
export type { RoutingDetails } from './src/models/RoutingDetails';
export { RoutingDetailsIfRule } from './src/models/RoutingDetailsIfRule';
export type { RoutingGet } from './src/models/RoutingGet';
export type { RoutingUpdate } from './src/models/RoutingUpdate';
export type { sepa } from './src/models/sepa';
export { Service } from './src/models/Service';
export type { Settlement } from './src/models/Settlement';
export type { skrill } from './src/models/skrill';
export type { sofort } from './src/models/sofort';
export type { SpendBacks } from './src/models/SpendBacks';
export type { SpendBackTxn } from './src/models/SpendBackTxn';
export { SpendBackTxnResp } from './src/models/SpendBackTxnResp';
export type { StatisticsDayAndTime } from './src/models/StatisticsDayAndTime';
export { StatisticsProcessorCompare } from './src/models/StatisticsProcessorCompare';
export { StatisticsProcessorRevenue } from './src/models/StatisticsProcessorRevenue';
export { StatisticsRecent } from './src/models/StatisticsRecent';
export type { StillInUse } from './src/models/StillInUse';
export { StoredUser } from './src/models/StoredUser';
export { Subscription } from './src/models/Subscription';
export type { SubscriptionCreate } from './src/models/SubscriptionCreate';
export { SubscriptionDiscount } from './src/models/SubscriptionDiscount';
export type { SubscriptionDiscountAttached } from './src/models/SubscriptionDiscountAttached';
export type { SubscriptionDiscountAttachedGet } from './src/models/SubscriptionDiscountAttachedGet';
export { SubscriptionDiscountCreate } from './src/models/SubscriptionDiscountCreate';
export type { SubscriptionDiscountGet } from './src/models/SubscriptionDiscountGet';
export type { SubscriptionDiscountUpdate } from './src/models/SubscriptionDiscountUpdate';
export type { SubscriptionGet } from './src/models/SubscriptionGet';
export type { SubscriptionUpdate } from './src/models/SubscriptionUpdate';
export type { Tag } from './src/models/Tag';
export type { TagCreate } from './src/models/TagCreate';
export type { TagGet } from './src/models/TagGet';
export type { TagUpdate } from './src/models/TagUpdate';
export type { TaxYearUserResp } from './src/models/TaxYearUserResp';
export { Terminal } from './src/models/Terminal';
export type { TerminalGet } from './src/models/TerminalGet';
export type { TooManyRequests } from './src/models/TooManyRequests';
export { Transaction } from './src/models/Transaction';
export type { TransactionAggregate } from './src/models/TransactionAggregate';
export type { TransactionAggregateDay } from './src/models/TransactionAggregateDay';
export type { TransactionAggregateLocation } from './src/models/TransactionAggregateLocation';
export type { TransactionAggregateStats } from './src/models/TransactionAggregateStats';
export type { TransactionAggregateStatsCount } from './src/models/TransactionAggregateStatsCount';
export type { TransactionAggregateStatsVolume } from './src/models/TransactionAggregateStatsVolume';
export type { TransactionAggregateTotal } from './src/models/TransactionAggregateTotal';
export type { TransactionCannotBeCaptured } from './src/models/TransactionCannotBeCaptured';
export type { TransactionCapture } from './src/models/TransactionCapture';
export type { TransactionCheckoutsuccess } from './src/models/TransactionCheckoutsuccess';
export type { TransactionCheckoutsuccessFailure } from './src/models/TransactionCheckoutsuccessFailure';
export type { TransactionCreate } from './src/models/TransactionCreate';
export type { TransactionDetailApplePay } from './src/models/TransactionDetailApplePay';
export type { TransactionDetailBancontact } from './src/models/TransactionDetailBancontact';
export type { TransactionDetailCard } from './src/models/TransactionDetailCard';
export type { TransactionDetailDefault } from './src/models/TransactionDetailDefault';
export { TransactionDetailDiscount } from './src/models/TransactionDetailDiscount';
export { TransactionDetailFraud } from './src/models/TransactionDetailFraud';
export type { TransactionDetailGet } from './src/models/TransactionDetailGet';
export type { TransactionDetailGooglePay } from './src/models/TransactionDetailGooglePay';
export type { TransactionDetailIdeal } from './src/models/TransactionDetailIdeal';
export { TransactionDetailMDR } from './src/models/TransactionDetailMDR';
export type { TransactionDetailPaypal } from './src/models/TransactionDetailPaypal';
export type { TransactionDetailSender } from './src/models/TransactionDetailSender';
export type { TransactionDetailVolt } from './src/models/TransactionDetailVolt';
export type { TransactionGet } from './src/models/TransactionGet';
export { TransactionHistory } from './src/models/TransactionHistory';
export { TransactionLifecycle } from './src/models/TransactionLifecycle';
export type { TransactionNotRefundable } from './src/models/TransactionNotRefundable';
export type { TransactionNotVoidable } from './src/models/TransactionNotVoidable';
export type { TransactionOrderData } from './src/models/TransactionOrderData';
export { TransactionOrderDataProductLines } from './src/models/TransactionOrderDataProductLines';
export type { TransactionOrderDataTotalLines } from './src/models/TransactionOrderDataTotalLines';
export type { TransactionStart } from './src/models/TransactionStart';
export type { triplea } from './src/models/triplea';
export type { trustly } from './src/models/trustly';
export type { trustpay } from './src/models/trustpay';
export { TxnHistoryResp } from './src/models/TxnHistoryResp';
export type { unionpay } from './src/models/unionpay';
export { UpdateUser } from './src/models/UpdateUser';
export type { upi } from './src/models/upi';
export type { User } from './src/models/User';
export type { UserForgotPassword } from './src/models/UserForgotPassword';
export { Users } from './src/models/Users';
export type { UserUpdateEmail } from './src/models/UserUpdateEmail';
export type { UserUpdatePassword } from './src/models/UserUpdatePassword';
export { ValidationRuleset } from './src/models/ValidationRuleset';
export { ValidationRulesetCreate } from './src/models/ValidationRulesetCreate';
export type { ValidationRulesetGet } from './src/models/ValidationRulesetGet';
export { ValidationRulesetRule } from './src/models/ValidationRulesetRule';
export type { ValidationRulesetRuleCreate } from './src/models/ValidationRulesetRuleCreate';
export type { ValidationRulesetRuleGet } from './src/models/ValidationRulesetRuleGet';
export type { ValidationRulesetUpdate } from './src/models/ValidationRulesetUpdate';
export type { volt } from './src/models/volt';
export { WalletTxnResp } from './src/models/WalletTxnResp';
export { Webhook } from './src/models/Webhook';
export { WebhookCreate } from './src/models/WebhookCreate';
export type { WebhookGet } from './src/models/WebhookGet';
export type { WebhookHistory } from './src/models/WebhookHistory';
export type { wechatpay } from './src/models/wechatpay';
export type { Whitelist } from './src/models/Whitelist';
export type { WhitelistCreate } from './src/models/WhitelistCreate';
export type { WhitelistGet } from './src/models/WhitelistGet';
export type { WhitelistUpdate } from './src/models/WhitelistUpdate';

export { AccountService } from './src/services/AccountService';
export { AttributeService } from './src/services/AttributeService';
export { CardService } from './src/services/CardService';
export { CatalogService } from './src/services/CatalogService';
export { KycService } from './src/services/KycService';
export { LoadService } from './src/services/LoadService';
export { PayoutService } from './src/services/PayoutService';
export { SpendBackService } from './src/services/SpendBackService';
export { SubaccountService } from './src/services/SubaccountService';
export { TaxService } from './src/services/TaxService';
export { UserService } from './src/services/UserService';
export { WalletService } from './src/services/WalletService';
